[package]
name = "spacehophelper14"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.40.0"
tao = "0.28.0"
image = "0.25.1"
